### ISSUE TITLE
Quick view in You May Also Like Products

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---Brittany-Store-Design---30-April-2022#12]
The quick view in You May Also Like products is not working.

![image](https://user-images.githubusercontent.com/97726944/164612659-f8be41b1-c25c-4695-becc-7654c46bd0c4.png)

**Comment by devSharibAli** [comment]
![image](https://user-images.githubusercontent.com/100212678/164729602-b91fa399-7e99-4d4b-9305-008f13049891.png)
