### ISSUE TITLE
Clear cart link/ button

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---Brittany-Store-Design---30-April-2022#14]
Instead of link we can use button for the clear cart.
https://5lq3xdnkpp9j650r-63357190372.shopifypreview.com/cart

![image](https://user-images.githubusercontent.com/97726944/164613242-ad3e2441-8b47-429f-a9aa-0a671a5a3d56.png)

**Comment by ui-abrarul** [comment]
As per arvind sir review we should not highlight clear cart button on cart page, its designed as per the reference shown to me by arvind sir.
