### ISSUE TITLE
Empty collection 

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---Brittany-Store-Design---30-April-2022#16]
Hair tool page is not showing any collection.
https://5lq3xdnkpp9j650r-63357190372.shopifypreview.com/collections/hair-tools

![image](https://user-images.githubusercontent.com/97726944/164614830-98c40691-70fb-409c-836e-6856fb99f9b4.png)

**Comment by devSharibAli** [comment]
Client will be adding products later
