### ISSUE TITLE
Arrow button alignment in Mac safari

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---Brittany-Store-Design---30-April-2022#25]
The arrow buttons are not properly aligned in Mac safari browser.

![image](https://user-images.githubusercontent.com/97726944/164628879-95299255-6c91-46dc-8bc7-06016146032b.png)

**Comment by ui-abrarul** [comment]
![Screenshot 2022-04-25 at 12 05 48 PM](https://user-images.githubusercontent.com/100340013/165048923-cdc76088-f813-4145-95e0-0567261db1c5.png)

**Comment by ui-abrarul** [comment]
issue not coming on office mac
