### ISSUE TITLE
Cropped banners in collection pages

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---Brittany-Store-Design---30-April-2022#6]
The banners used in header looks like they are cropping in all the collection pages.

![image](https://user-images.githubusercontent.com/97726944/164606917-e4ad1407-0c52-457e-bc1c-b9a33197d150.png)

**Comment by ui-abrarul** [comment]
Banners are not cropped, 1920*250 sized banner has been used on collection pages.
Original banner link: https://cdn.shopify.com/s/files/1/0633/5719/0372/collections/accesories.jpg
